/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sara.sprettypicks;
import java.awt.Component;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarar
 */
public class Admindashboardfacade extends javax.swing.JFrame {

    /**
     * Creates new form Admindashboard
     */
    public Admindashboardfacade() {
        initComponents();
        setUserNameInTextFieldadmin();
    }
 private void setUserNameInTextFieldadmin() {
    String username = SessionManager.getLoggedInUserName(); // Assuming you have a method to get the logged-in username.
    
    // Set the username in jTextField2
    //jTextField2.setText(username);
    admin.setText(username);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addproducts = new javax.swing.JButton();
        deleteproducts = new javax.swing.JButton();
        showproducts = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Product_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        addproducts.setBackground(new java.awt.Color(153, 255, 102));
        addproducts.setText("Add Products");
        addproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproductsActionPerformed(evt);
            }
        });

        deleteproducts.setBackground(new java.awt.Color(153, 255, 102));
        deleteproducts.setText("Delete Products");
        deleteproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproductsActionPerformed(evt);
            }
        });

        showproducts.setBackground(new java.awt.Color(153, 255, 102));
        showproducts.setText("View Products");
        showproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showproductsActionPerformed(evt);
            }
        });

        jButton5.setText("View Customers");

        jButton6.setText("Delete Customers");

        jButton7.setText("Show Reviews");

        jButton8.setText("View Purchasing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(addproducts)
                .addGap(29, 29, 29)
                .addComponent(deleteproducts)
                .addGap(33, 33, 33)
                .addComponent(showproducts)
                .addGap(24, 24, 24)
                .addComponent(jButton5)
                .addGap(33, 33, 33)
                .addComponent(jButton6)
                .addGap(34, 34, 34)
                .addComponent(jButton7)
                .addGap(30, 30, 30)
                .addComponent(jButton8)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        Product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Prod_id", "Prod_name", "price", "prod_category", "prod_description", "quantity"
            }
        ));
        jScrollPane1.setViewportView(Product_table);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Admin Dashboard");

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setText("Sign out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        admin.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        admin.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(236, 236, 236)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(admin))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1618, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproductsActionPerformed
        Addproducts ob=new Addproducts();
        ob.setVisible(true);
         //setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addproductsActionPerformed

    private void deleteproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproductsActionPerformed
 // Get the selected row index
int selectedRow = Product_table.getSelectedRow();

if (selectedRow == -1) {
    // No row is selected, show an error message
    JOptionPane.showMessageDialog(this, "Please select a product to delete.");
    return;
}

// Get the product ID from the selected row (assuming it's in the first column)
DefaultTableModel tableModel = (DefaultTableModel) Product_table.getModel();
String productId = tableModel.getValueAt(selectedRow, 0).toString();

// Confirm the deletion action
int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
if (confirm != JOptionPane.YES_OPTION) {
    return; // If user clicks 'No', exit the method
}

// Database instance
Database db = Database.getInstance();
Connection conn = null;

try {
    // Establish the connection
    conn = db.connect();
    conn.setAutoCommit(false);  // Start transaction

    // Step 1: Check if the product exists in the cart table
    String checkCartSql = "SELECT COUNT(*) FROM cart WHERE product_id = ?";
    PreparedStatement checkCartStmt = conn.prepareStatement(checkCartSql);
    checkCartStmt.setString(1, productId);

    ResultSet cartResult = checkCartStmt.executeQuery();
    cartResult.next(); // Move to the first result
    int cartCount = cartResult.getInt(1); // Get the count of rows with this product_id in the cart table

    System.out.println("Cart Count: " + cartCount); // Debugging statement to check cart count

    cartResult.close();
    checkCartStmt.close();

    if (cartCount > 0) {
        // If the product exists in the cart table, delete it from the cart first
        String deleteFromCartSql = "DELETE FROM cart WHERE product_id = ?";
        PreparedStatement deleteFromCartStmt = conn.prepareStatement(deleteFromCartSql);
        deleteFromCartStmt.setString(1, productId);
        int cartRowsDeleted = deleteFromCartStmt.executeUpdate();
        System.out.println("Rows deleted from cart: " + cartRowsDeleted);  // Debugging statement to check if item was deleted
        deleteFromCartStmt.close();

        // Now show a message to the user that the product was removed from the cart
        JOptionPane.showMessageDialog(this, "Product was removed from the cart.");
    }

    // Step 2: Delete the product from the products table
    String deleteProductSql = "DELETE FROM products WHERE product_id = ?";
    PreparedStatement productStmt = conn.prepareStatement(deleteProductSql);
    productStmt.setString(1, productId);

    int rowsDeleted = productStmt.executeUpdate(); // Execute the deletion from the products table
    System.out.println("Rows deleted from products table: " + rowsDeleted);  // Debugging statement

    productStmt.close();

    if (rowsDeleted > 0) {
        // If the deletion was successful, remove the row from the table
        tableModel.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Product deleted successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "Error: Product not found in the database.");
    }

    // Commit the transaction
    conn.commit();

} catch (SQLException ex) {
    // Handle SQLException which may include foreign key constraint violation
    if (conn != null) {
        try {
            // Rollback in case of an error
            conn.rollback();
        } catch (SQLException rollbackEx) {
            rollbackEx.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error during rollback: " + rollbackEx.getMessage());
        }
    }

    // Handle specific error codes
    if (ex.getErrorCode() == 1451) { // MySQL error code for foreign key constraint violation
       // JOptionPane.showMessageDialog(this, "Cannot delete the product. It is currently in someone's cart. Please remove it from the cart first.");
    } else {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error deleting product from the database: " + ex.getMessage());
    }
} finally {
    // Ensure the connection is closed regardless of success or failure
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException closeEx) {
            closeEx.printStackTrace();
        }
    }
}


    }//GEN-LAST:event_deleteproductsActionPerformed

    private void showproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showproductsActionPerformed
             Database db = Database.getInstance();
// Clear existing rows in the table before showing products
DefaultTableModel tableModel = (DefaultTableModel) Product_table.getModel();
tableModel.setRowCount(0);

try {
    // Retrieve the database connection
    Connection conn = db.connect();
    
    // SQL query to retrieve all products (excluding image)
    String sql = "SELECT product_id, name, price, category, description, quantity FROM products";
    PreparedStatement pstmt = conn.prepareStatement(sql);
    
    ResultSet rs = pstmt.executeQuery();
    
    while (rs.next()) {
        String productId = rs.getString("product_id");
        String productName = rs.getString("name");
        double price = rs.getDouble("price");
        String category = rs.getString("category");
        String description = rs.getString("description");
        int quantity = rs.getInt("quantity");

        // Add product row to the table without image
        tableModel.addRow(new Object[]{productId, productName, price, category, description, quantity});
    }
    
    rs.close();
    pstmt.close();
    
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error retrieving product data from the database.");
}

    }//GEN-LAST:event_showproductsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginformfacade logout=new loginformfacade();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admindashboardfacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admindashboardfacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admindashboardfacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admindashboardfacade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admindashboardfacade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Product_table;
    private javax.swing.JButton addproducts;
    private javax.swing.JLabel admin;
    private javax.swing.JButton deleteproducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showproducts;
    // End of variables declaration//GEN-END:variables
}
